server:
  port: 8081
spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: dev
  application:
    name: hmdp
mybatis-plus:
  type-aliases-package: com.hmdp.entity # 别名扫描包
logging:
  level:
    com.hmdp: debug
  pattern:
    dateformat: mm:ss.SSS